mode: rule
log-level: info

external-controller: 0.0.0.0:9090
external-ui: ui

tun:
  enable: true
  stack: gvisor
  device: Mihomo
  dns-hijack:
    - any:53

dns:
  enable: true
  listen: :53
  ipv6: true
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: false
  nameserver:
    - 'https://doh.pub/dns-query'
    - 'https://dns.alidns.com/dns-query'

profile:
  store-selected: true
  store-fake-ip: true

proxies:
  - name: "PROXY"
    type: ss
    server: 120.198.71.191
    port: 29467
    cipher: chacha20-ietf-poly1305
    password: password
    udp: true

rules:
  - DOMAIN-SUFFIX,jianguoyun.com,PROXY
  - DOMAIN-SUFFIX,github.com,PROXY
  - DOMAIN-SUFFIX,deepseek.com,PROXY
  - DOMAIN-KEYWORD,csdn,PROXY
  # LAN
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  # Final
  - MATCH,DIRECT

